services:

  backend:
    image: hdfcas03/as03-backend-2:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      ENV: ${ENV}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
    networks:
      - app-network

  gateway:
    image: hdfcas03/as03-gateway-2:latest
    container_name: api-gateway
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      JWKS_URL: ${JWKS_URL}
      JWT_ISSUER_1: ${JWT_ISSUER_1}
      JWT_ISSUER_2: ${JWT_ISSUER_2}
      JWKS_CACHE_TTL: ${JWKS_CACHE_TTL}
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    image: hdfcas03/as03-frontend-2:latest
    container_name: as03-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge