version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    # Added --proxy edge to support the Nginx Gateway routing
    command: start-dev --http-relative-path /auth --proxy edge
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=superadmin
      - KEYCLOAK_ADMIN_PASSWORD=hdfcintern
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  backend:
    build:
      context: ../AS-03-Backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_EXTERNAL_URL=http://18.214.226.2:8080/auth
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYCLOAK_ADMIN_CLIENT_SECRET=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - FRONTEND_URL=http://18.214.226.2:3000
      - ENV=dev
    depends_on:
      - keycloak
    networks:
      - app-network

  gateway:
    build:
      context: ../AS-03-Backend/gateway
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ../AS-03-Backend/gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ../AS-03-Backend/gateway/lua:/usr/local/openresty/nginx/lua
    depends_on:
      - backend
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  frontend:
    build:
      context: ../AS-03-Frontend
    container_name: as03-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: